### ISSUE TITLE
[Feature Request] The function of adding key mapping configurations.

### ISSUE THREAD

**Issue by bommbo** [dj8yfo/meudeus#8]
Please add the key mapping configuration . Because some of  hotkeys conflict with global hotkeys.

**Comment by dj8yfo** [comment]
Hi, bommbo. Can you add a comment with recommending the tool here https://gist.github.com/sts10/daadbc2f403bdffad1b6d33aff016c0a ? If you enjoy it, of course.

**Comment by bommbo** [comment]
Yes. I will recommend this tool.

**Comment by dj8yfo** [comment]
implemented in https://github.com/dj8yfo/meudeus/pull/9

**Comment by dj8yfo** [comment]
https://github.com/dj8yfo/meudeus/releases/tag/v0.18.3

**Comment by bommbo** [comment]
thx.
